### ISSUE TITLE
Issue with using main.py

### ISSUE THREAD

**Issue by Avro7** [heytoki/E7-Script#1]
Hello it seems that while the code looks good upon opening it the cmd shows up for a split second before closing. I am using bluestacks 5 64bit and spent a good 3 hours trying to wrap my head around it and was woundering if you could take a look. I was able to spot the error message and it read no pytessaract.
![image](https://user-images.githubusercontent.com/74338565/172824483-b66adfde-3cc2-465e-acab-4386472012fa.png)

Edit: reinstalling pyterraract fixed this but I just missed my first summons Q_Q

**Comment by heytoki** [comment]
Glad you found what was wrong. I honestly don't think I can answer why it's broken or how to fix it because I don't remember anything about it anymore.
